# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Rename-Item -Path "helloworld.war" -NewName "helloworld.$(Build.BuildId).war"'
    workingDirectory: '$(build.artifactstagingdirectory)/s/target'
- task: OctopusPush@6
  inputs:
    OctoConnectedServiceName: 'demo'
    Space: 'Default'
    Packages: '$(build.artifactstagingdirectory)/s/target/helloworld.$(Build.BuildId).war'
    Replace: 'false'
- task: OctopusCreateRelease@6
  inputs:
    OctoConnectedServiceName: 'demo'
    Space: 'Default'
    Project: 'octopusjava'
- task: OctopusDeployRelease@6
  inputs:
    OctoConnectedServiceName: 'demo'
    Space: 'Default'
    Project: 'octopusjava'
    ReleaseNumber: '0.0.1'
    Environments: 'Development'